name: "Felastrap CI/CD"

on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Check Formatting
        run: yarn format:check

      - name: Unit Tests with coverage
        run: yarn test --ci --coverage
  storybook:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4   
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: yarn install --frozen-lockfile
          build_command: yarn build-storybook
          path: storybook-static
          checkout: false

    