name: "Felastrap CI Actions"

on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@4"
      - name: Setup Node
        uses: actions/setup-node@3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Check Formatting
        run: yarn format:check

      - name: Unit Tests with coverage
        run: yarn test --ci --coverage
